import type { EmailLog, FollowUpTask, Lead, Meeting, SalesUser, WhatsAppLog } from "./types";

export const salesUsers: SalesUser[] = [
  { id: "user-1", name: "AXDCARE Sales Team", email: "sales@axdcare.com", role: "Sales Manager", timezone: "Asia/Shanghai" },
];

export const leads: Lead[] = [
  {
    id: "lead-1",
    company: { id: "co-1", name: "Nordlicht Medical Distribution", country: "Germany", city: "Berlin", region: "Europe", website: "https://nordlicht-med.example", businessType: "Distributor", size: "Large" },
    contact: { id: "ct-1", companyId: "co-1", firstName: "Lena", lastName: "Fischer", title: "Sourcing Manager", email: "lena@nordlicht.example", phone: "+49 30 0000", whatsapp: "+49300000" },
    importRecord: { id: "im-1", companyName: "Nordlicht Medical Distribution", country: "Germany", city: "Berlin", importerName: "Lena Fischer", productDescription: "Digital blood pressure monitor and nebulizer medical devices", hsCode: "901890", shipmentCount: 18, shipmentValue: 168000, supplierCountry: "China", website: "https://nordlicht-med.example", email: "lena@nordlicht.example", phone: "+49 30 0000", whatsapp: "+49300000", source: "Mock customs data" },
    productInterest: "Blood Pressure Monitor",
    matchedAxdProduct: "Blood Pressure Monitor",
    status: "AI Researched",
    priority: "High",
    lastContactAt: "2026-06-24",
    nextFollowUpAt: "2026-06-28T09:30:00+02:00",
    aiBackgroundSummary: "German distributor with repeated home healthcare imports and a complete buyer contact profile. Strong fit for OEM blood pressure monitor follow-up.",
    recommendedProducts: ["Upper Arm Blood Pressure Monitor", "Mesh Nebulizer", "Infrared Thermometer"],
    notes: ["Ask about MDR documentation expectations.", "Lead prefers concise product comparison tables."],
    ownerId: "user-1",
  },
  {
    id: "lead-2",
    company: { id: "co-2", name: "Iberia Health Trade", country: "Spain", city: "Madrid", region: "Europe", website: "https://iberia-health.example", businessType: "Medical Wholesaler", size: "Medium" },
    contact: { id: "ct-2", companyId: "co-2", firstName: "Mateo", lastName: "Ruiz", title: "Import Director", email: "mateo@iberia.example", whatsapp: "+34600000000" },
    importRecord: { id: "im-2", companyName: "Iberia Health Trade", country: "Spain", city: "Madrid", importerName: "Mateo Ruiz", productDescription: "Compressor nebulizer and medical respiratory care accessories", hsCode: "901920", shipmentCount: 12, shipmentValue: 92000, supplierCountry: "China", website: "https://iberia-health.example", email: "mateo@iberia.example", whatsapp: "+34600000000", source: "Mock customs data" },
    productInterest: "Compressor Nebulizer",
    matchedAxdProduct: "Compressor Nebulizer",
    status: "Email Drafted",
    priority: "High",
    lastContactAt: "2026-06-22",
    nextFollowUpAt: "2026-06-28T10:30:00+02:00",
    aiBackgroundSummary: "Spain-based medical wholesaler importing respiratory care products. Good candidate for compressor nebulizer catalog and MOQ discussion.",
    recommendedProducts: ["Compressor Nebulizer", "Mesh Nebulizer"],
    notes: ["Follow up with Spanish-market packaging questions."],
    ownerId: "user-1",
  },
  {
    id: "lead-3",
    company: { id: "co-3", name: "SunArc Medical Solutions", country: "United Arab Emirates", city: "Dubai", region: "Middle East", website: "https://sunarc-med.example", businessType: "Importer", size: "Large" },
    contact: { id: "ct-3", companyId: "co-3", firstName: "Noor", lastName: "Haddad", title: "Procurement Lead", email: "noor@sunarc.example", phone: "+971 4 0000", whatsapp: "+97150000000" },
    importRecord: { id: "im-3", companyName: "SunArc Medical Solutions", country: "United Arab Emirates", city: "Dubai", importerName: "Noor Haddad", productDescription: "Infrared thermometer and home medical monitoring devices", hsCode: "902519", shipmentCount: 15, shipmentValue: 135000, supplierCountry: "China", website: "https://sunarc-med.example", email: "noor@sunarc.example", phone: "+971 4 0000", whatsapp: "+97150000000", source: "Mock customs data" },
    productInterest: "Infrared Thermometer",
    matchedAxdProduct: "Infrared Thermometer",
    status: "Quoted",
    priority: "High",
    lastContactAt: "2026-06-25",
    nextFollowUpAt: "2026-06-29T14:30:00+04:00",
    aiBackgroundSummary: "Active Gulf importer with broad medical device portfolio. Quotation follow-up should focus on certifications and carton packing.",
    recommendedProducts: ["Infrared Thermometer", "Blood Pressure Monitor"],
    notes: ["Prepare updated quote before WhatsApp follow-up."],
    ownerId: "user-1",
  },
  {
    id: "lead-4",
    company: { id: "co-4", name: "PharmaPlus Retail Group", country: "United States", city: "New York", region: "North America", website: "https://pharmaplus.example", businessType: "Pharmacy Chain", size: "Enterprise" },
    contact: { id: "ct-4", companyId: "co-4", firstName: "Avery", lastName: "Cole", title: "Category Buyer", email: "avery@pharmaplus.example", phone: "+1 212 000 0000" },
    importRecord: { id: "im-4", companyName: "PharmaPlus Retail Group", country: "United States", city: "New York", importerName: "Avery Cole", productDescription: "Retail pharmacy blood pressure monitor private label", hsCode: "901890", shipmentCount: 21, shipmentValue: 244000, supplierCountry: "China", website: "https://pharmaplus.example", email: "avery@pharmaplus.example", phone: "+1 212 000 0000", source: "Mock customs data" },
    productInterest: "Private label blood pressure monitor",
    matchedAxdProduct: "Blood Pressure Monitor",
    status: "New Lead",
    priority: "High",
    lastContactAt: undefined,
    nextFollowUpAt: "2026-06-28T11:00:00-04:00",
    aiBackgroundSummary: "Large pharmacy chain profile with private label relevance. Needs careful manual review before any outreach.",
    recommendedProducts: ["Upper Arm Blood Pressure Monitor", "Wrist Blood Pressure Monitor"],
    notes: ["Do not send until buyer role is verified."],
    ownerId: "user-1",
  },
  {
    id: "lead-5",
    company: { id: "co-5", name: "Island Medical Online", country: "Philippines", city: "Manila", region: "Asia", businessType: "E-commerce Seller", size: "Small" },
    contact: { id: "ct-5", companyId: "co-5", firstName: "Paolo", lastName: "Santos", title: "Owner", email: "paolo@islandmedical.example", whatsapp: "+639000000000" },
    importRecord: { id: "im-5", companyName: "Island Medical Online", country: "Philippines", city: "Manila", importerName: "Paolo Santos", productDescription: "Portable nebulizer for online retail", hsCode: "901920", shipmentCount: 6, shipmentValue: 28000, supplierCountry: "China", email: "paolo@islandmedical.example", whatsapp: "+639000000000", source: "Mock customs data" },
    productInterest: "Mesh Nebulizer",
    matchedAxdProduct: "Mesh Nebulizer",
    status: "Email Sent",
    priority: "Medium",
    lastContactAt: "2026-06-24",
    nextFollowUpAt: "2026-06-30T10:00:00+08:00",
    aiBackgroundSummary: "Smaller e-commerce seller with relevant nebulizer imports. Best handled with catalog and low MOQ positioning.",
    recommendedProducts: ["Mesh Nebulizer", "Infrared Thermometer"],
    notes: ["Ask about marketplace channel and packaging limits."],
    ownerId: "user-1",
  },
  {
    id: "lead-6",
    company: { id: "co-6", name: "Southern Care Wholesale", country: "Australia", city: "Sydney", region: "Oceania", website: "https://southerncare.example", businessType: "Medical Wholesaler", size: "Medium" },
    contact: { id: "ct-6", companyId: "co-6", firstName: "Mia", lastName: "Wilson", title: "Product Manager", email: "mia@southerncare.example", phone: "+61 2 0000 0000" },
    importRecord: { id: "im-6", companyName: "Southern Care Wholesale", country: "Australia", city: "Sydney", importerName: "Mia Wilson", productDescription: "Healthcare thermometer and blood pressure monitor", hsCode: "901890", shipmentCount: 9, shipmentValue: 74000, supplierCountry: "China", website: "https://southerncare.example", email: "mia@southerncare.example", phone: "+61 2 0000 0000", source: "Mock customs data" },
    productInterest: "Thermometer and BP monitor",
    matchedAxdProduct: "Infrared Thermometer",
    status: "Meeting Scheduled",
    priority: "High",
    lastContactAt: "2026-06-26",
    nextFollowUpAt: "2026-07-01T09:00:00+10:00",
    aiBackgroundSummary: "Australia wholesaler with meeting scheduled. Prepare product comparison and compliance summary.",
    recommendedProducts: ["Infrared Thermometer", "Blood Pressure Monitor"],
    notes: ["Meeting agenda: product range, certifications, lead time."],
    ownerId: "user-1",
  },
  {
    id: "lead-7",
    company: { id: "co-7", name: "Andes Health Import", country: "Colombia", city: "Bogota", region: "Latin America", businessType: "Importer", size: "Medium" },
    contact: { id: "ct-7", companyId: "co-7", firstName: "Camila", lastName: "Torres", title: "Purchasing", email: "camila@andeshealth.example" },
    importRecord: { id: "im-7", companyName: "Andes Health Import", country: "Colombia", city: "Bogota", importerName: "Camila Torres", productDescription: "Medical nebulizer and homecare accessories", hsCode: "901920", shipmentCount: 8, shipmentValue: 51000, supplierCountry: "China", email: "camila@andeshealth.example", source: "Mock customs data" },
    productInterest: "Nebulizer",
    matchedAxdProduct: "Mesh Nebulizer",
    status: "AI Researched",
    priority: "Medium",
    lastContactAt: "2026-06-21",
    nextFollowUpAt: "2026-06-28T09:00:00-05:00",
    aiBackgroundSummary: "Importer with recurring nebulizer activity. Contact profile is partial, so verify WhatsApp before direct messaging.",
    recommendedProducts: ["Mesh Nebulizer", "Compressor Nebulizer"],
    notes: ["Spanish catalog may improve response."],
    ownerId: "user-1",
  },
  {
    id: "lead-8",
    company: { id: "co-8", name: "Cape Health Works", country: "South Africa", city: "Johannesburg", region: "Africa", website: "https://capehealth.example", businessType: "Distributor", size: "Medium" },
    contact: { id: "ct-8", companyId: "co-8", firstName: "Amara", lastName: "Jacobs", title: "Director", email: "amara@capehealth.example", whatsapp: "+27000000000" },
    importRecord: { id: "im-8", companyName: "Cape Health Works", country: "South Africa", city: "Johannesburg", importerName: "Amara Jacobs", productDescription: "Home healthcare device distributor blood pressure monitor", hsCode: "901890", shipmentCount: 11, shipmentValue: 87000, supplierCountry: "China", website: "https://capehealth.example", email: "amara@capehealth.example", whatsapp: "+27000000000", source: "Mock customs data" },
    productInterest: "Blood Pressure Monitor",
    matchedAxdProduct: "Blood Pressure Monitor",
    status: "Sample Requested",
    priority: "High",
    lastContactAt: "2026-06-26",
    nextFollowUpAt: "2026-06-29T11:00:00+02:00",
    aiBackgroundSummary: "Distributor has requested sample information. Next step is sample packing, cost and estimated delivery.",
    recommendedProducts: ["Blood Pressure Monitor", "Infrared Thermometer"],
    notes: ["Send sample checklist draft for review."],
    ownerId: "user-1",
  },
];

export const followUpTasks: FollowUpTask[] = leads.map((lead, index) => ({
  id: `task-${index + 1}`,
  leadId: lead.id,
  dueAt: lead.nextFollowUpAt,
  type: index % 3 === 0 ? "Email" : index % 3 === 1 ? "WhatsApp" : "Call",
  title: `Follow up with ${lead.company.name}`,
  completed: false,
}));

export const emailLogs: EmailLog[] = [
  { id: "email-1", leadId: "lead-2", sentAt: "2026-06-22T10:00:00+02:00", subject: "OEM Blood Pressure Monitor & Nebulizer Supply Support", opened: true },
  { id: "email-2", leadId: "lead-6", sentAt: "2026-06-26T09:20:00+10:00", subject: "Catalog and quotation support", opened: true, replied: true },
];

export const whatsAppLogs: WhatsAppLog[] = [
  { id: "wa-1", leadId: "lead-8", sentAt: "2026-06-26T14:00:00+02:00", message: "Sample details shared for review.", replied: true },
];

export const meetings: Meeting[] = [
  { id: "meeting-1", leadId: "lead-6", scheduledAt: "2026-07-01T09:00:00+10:00", topic: "Australia wholesale product review", status: "Scheduled" },
  { id: "meeting-2", leadId: "lead-8", scheduledAt: "2026-06-30T16:00:00+02:00", topic: "Sample request discussion", status: "Scheduled" },
];
